### ISSUE TITLE
Add migration instructions for older apps

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solidproject.org#607] opened 2021-08-03 17:39 UTC
**Search terms you've used**

NSS, app migration

**What problem are you trying to solve? Please describe.**

We need instructions on how to upgrade apps that use the v.0.7.0 draft to bring them to the latest specification.

**What existing documentation is relevant to your problem, and why is it insufficient?**

- https://github.com/solid/solid-spec

**Comment by NoelDeMartin** [comment] 2021-08-14 16:09
I started making Solid apps exclusively on NSS and trying other servers (not just CSS) I've found a couple of things I needed to change, so maybe it's useful if I share the main ones that come to mind.

To clarify, these are things that Solid apps should NOT use:

- [Globbing](https://github.com/solid/solid-spec/blob/master/api-rest.md#globbing-inlining-on-get) - It's at risk of being [changed](https://github.com/solid/solid-spec/pull/148) or [removed](https://github.com/solid/solid-spec/pull/151).
- `posix:mtime` and `purl:modified` for container resources - This [is not part of the spec](https://github.com/solid/specification/issues/227#issuecomment-773945439) yet.
- [`solid-auth-client`](https://github.com/solid/solid-auth-client) - It [doesn't support DPoP authentication](https://github.com/NoelDeMartin/media-kraken/issues/9), you should use [@inrupt/solid-authn-client-browser](https://github.com/inrupt/solid-client-authn-js/) or something else instead. Related with that, [your app won't stay logged in after refresh](https://github.com/inrupt/solid-client-authn-js/issues/423).
- `pim:storage` in the profile - It can exist, but if it doesn't you should [move up the URI path hierarchy](https://solid.github.io/specification/protocol#storage).
- [The type index](https://github.com/solid/solid/blob/main/proposals/data-discovery.md#type-index-registry) - It can exist, but if it doesn't [you can create it](https://github.com/solid/community-server/issues/839#issuecomment-885516356). Although [that's not recommended either](https://gitter.im/solid/data-interoperability-panel?at=610cea267bc44d0a47090d1e). I'm still learning about this, so I can't say much about the proper way to do it.

**Comment by jeff-zucker** [comment] 2021-08-14 16:20
Great list @NoelDeMartin.  I would change your second paragraph to "things your app should NOT depend on".  We certainly can use typeIndex, mtime, etc. when they are available, there is nothing wrong with a server making them available, what's wrong is counting on them to be there.  The use of solid-auth-client probably, unlike the others, should be in the do not use list.

**Comment by NoelDeMartin** [comment] 2021-08-14 17:15
Thanks for the suggestion @jeff-zucker, I just edited it. I'll leave `solid-auth-client` in the same list because I still use it in my apps,  it works better with old versions of NSS than Inrupt's client. But it's not the default authentication option.

**Comment by Vinnl** [comment] 2021-08-16 10:14
@NoelDeMartin `pim:storage` in the profile _should_ exist, according to the spec [according to @csarven](https://gitter.im/solid/specification?at=61017a7b1a1db149e9e78e88):

> Clients can discover a storage by making an HTTP GET request on the target URL to retrieve an RDF representation [RDF11-CONCEPTS], whose encoded RDF graph contains a relation of type http://www.w3.org/ns/pim/space#storage. The object of the relation is the storage (pim:Storage).

@matthieubosquet said he was going to respond to that, because he believed servers _didn't_ need to (which is why CSS doesn't), but hasn't done yet at this point in time. So so far, it looks like we _should_ be able to assume we can determine the storage, and that the fact that CSS doesn't is a bug in CSS.

**Comment by RubenVerborgh** [comment] 2021-08-16 10:16
> the fact that CSS doesn't is a bug in CSS

Please file an issue; but the profile is a user-editable document so not enforceable by any server.
We can list it in the template for creating pods though.

**Comment by Vinnl** [comment] 2021-08-16 10:20
I didn't report it because Matthieu said it was intentionally left out, but reported here now: https://github.com/solid/community-server/issues/910 Listing it in the template sounds perfectly fine to me.

**Comment by csarven** [comment] 2021-08-16 10:48
The Protocol does not require that a profile includes pim:storage. I don't think it is a CSS bug.

But @Vinnl I think what @NoelDeMartin is referring to this instead:

>Clients can determine the storage of a resource by moving up the URI path hierarchy until the response includes a Link header with rel="type" targeting http://www.w3.org/ns/pim/space#Storage. Clients may check the root path of a URI for the storage claim at any time.

and for that yes the server is required to:

>Servers exposing the storage resource MUST advertise by including the HTTP Link header with rel="type" targeting http://www.w3.org/ns/pim/space#Storage when responding to storage’s request URI.

I don't know if that's a CSS bug or not.

---

>Although that's not recommended either.

Some claiming "legacy" is not the same as consensus :)

**Comment by RubenVerborgh** [comment] 2021-08-16 10:50
> I don't know if that's a CSS bug or not.

It's not

```
$ curl -I https://css.verborgh.org/
HTTP/2 200
date: Mon, 16 Aug 2021 10:50:01 GMT
content-type: text/turtle
vary: Accept-Encoding
vary: Accept,Authorization,Origin
x-powered-by: Community Solid Server
updates-via: wss://css.verborgh.org/
access-control-allow-origin: *
access-control-allow-credentials: true
access-control-expose-headers: Accept-Patch,Link,Location,MS-Author-Via,Updates-Via,WAC-Allow
accept-patch: application/sparql-update
allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE
ms-author-via: SPARQL
link: <http://www.w3.org/ns/pim/space#Storage>; rel="type"
link: <http://www.w3.org/ns/ldp#Container>; rel="type"
link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"
link: <http://www.w3.org/ns/ldp#Resource>; rel="type"
link: <https://css.verborgh.org/.acl>; rel="acl"
wac-allow: user="read",public="read"
strict-transport-security: max-age=63072000
```

**Comment by matthieubosquet** [comment] 2021-08-16 10:59
This is not a bug in CSS.

> Clients **can** discover a storage by ...

1. That is not a MUST
2. If a MUST related to that existed, then all resources served by a Solid server would include an authoritative statement pointing to their storage
3. However, there is nothing mandating that a WebID is stored in a Solid server, besides that, any number of storages might be "owned" by a WebID AND there is no requirement for a storage to advertise its owner (so, by extension, there should be no requirement for a WebID to advertise all the storages it owns)

So to [your question](https://gitter.im/solid/specification?at=61017a7b1a1db149e9e78e88) @Vinnl:

> if someone logs in to my app with their WebID, how do I figure out where to store some particular data?

I'm afraid, there is no answer.

An application can not and for that matters, will never be able to consistently determine where to store data based on the WebID used in the session.

Probably that moving up the path URI can help a little in some cases, that is if: the server decides to advertise its owner AND the WebID is stored in a Solid server AND the Solid server used to serve the WebID is where the user wants to store that "particular data".

In truth, the user will and should have a way to determine where data is stored and that's quite complex and prone to judgement calls and errors.

As @justinwb [mentioned in gitter](https://gitter.im/solid/specification?at=61017a0fb8422d6f4f0ea7c3), those questions are being addressed in the [data interoperability panel](https://github.com/solid/data-interoperability-panel). But I'm afraid, there is no consensus or standard way to answer your question. In any case, I think apps will need to keep track of storages and provide adequate help for users to chose where to store their data.

**Comment by Vinnl** [comment] 2021-08-16 11:01
@matthieubosquet I took it back to Gitter since it's not really related to this issue or even this repository, so hard to track for people it might be relevant to: https://gitter.im/solid/specification?at=611a44153eec6d41d15c0c09

**Comment by RubenVerborgh** [comment] 2021-08-28 08:39
@jeff-zucker The spec is looking for input on this specific topic: https://github.com/solid/specification/issues/227

But this specific requirement seems hard to specify because of content negotiation. Resources do not have a content type; representations do.

So yes, an issue on solid-panes.

**Comment by bourgeoa** [comment] 2021-08-29 13:04
@jeff-zucker @RubenVerborgh

Some specifications are the result of existing specifications and implementations depending on maturing ideas and server implementations.

Here the problem has I see it is that : 
- contentType is a MUST on create and it is surprising not to be able to be returned back in container. A resource is defined by a pair of content and content-type. This pair can have different representation but it does not seem the point here in displaying container content.
- it is available in GET or HEAD and there is no other way to find it, even on NSS or CSS the resource name cannot give you the contentType

The argument of representation does seem to me something else and not related to returning the resource contentType used on creation or update

So yes there is an issue in dataBrowser and all apps using the container to find the contentType, if the contentType is not available in the container.
The solution of doing a HEAD from browser is much heavier than server side.

**Closed** 2023-11-10 09:19 UTC
